import React from 'react'

function About() {
  return (
    <div className="page about-page">
      <h1>About create-a-ip-tv-services-can-user-can-see-all-count</h1>
      <p>This project was generated by EditzwebZ, an AI-powered website generator.</p>
      <p>Developed by AshenEditZ with ❤️</p>
    </div>
  )
}

export default About