import React from 'react'

function Footer() {
  return (
    <footer className="footer">
      <p>&copy; {new Date().getFullYear()} create-a-ip-tv-services-can-user-can-see-all-count</p>
      <p>Generated by EditzwebZ - Developed by AshenEditZ</p>
    </footer>
  )
}

export default Footer